#!/bin/bash

conda install -c conda-forge nodejs

pip install jupyterlab==3

#mkdir build_lab
#cd build_lab
pip install ipywidgets

#pip install jp_proxy_widget

jupyter labextension install @jupyter-widgets/jupyterlab-manager  --no-build
jupyter labextension install jp_proxy_widget

#pip install https://github.com/AaronWatters/jp_doodle/zipball/master
